services:
  tss-vuepress:
    container_name: "tss-container"
    image: "tss-image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -host 0.0.0.0
